apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blogging-srv-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blogging-srv
                port:
                  number: 80