apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka
  name: kafka
spec:
  clusterIP: None
  selector:
    service: kafka
  ports:
    - name: internal
      port: 9093
      targetPort: 9093
    - name: external
      port: 9092
      targetPort: 9092